package jpegn

import (
	"bytes"
	"fmt"
	"math"
	"math/rand"
	"testing"
)

// idctTestBlock is a set of DCT coefficients used as input for the test.
// This block has a single non-zero DC coefficient (512) and all AC coefficients are zero.
// The IDCT of such a block should result in a flat 8x8 block where every pixel has the same value.
var idctTestBlock = [64]int32{
	512, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
}

// idctTestPixels is the expected 8x8 pixel block output after applying the IDCT.
// The result should be a flat block where every pixel value is 192.
// This is calculated as (512 / 8) + 128 = 64 + 128 = 192.
var idctTestPixels = [64]byte{
	192, 192, 192, 192, 192, 192, 192, 192,
	192, 192, 192, 192, 192, 192, 192, 192,
	192, 192, 192, 192, 192, 192, 192, 192,
	192, 192, 192, 192, 192, 192, 192, 192,
	192, 192, 192, 192, 192, 192, 192, 192,
	192, 192, 192, 192, 192, 192, 192, 192,
	192, 192, 192, 192, 192, 192, 192, 192,
	192, 192, 192, 192, 192, 192, 192, 192,
}

// idctTestBlockAC is a test block with non-zero AC coefficients to test the main transform logic.
var idctTestBlockAC = [64]int32{
	0, 20, 0, 0, 0, 0, 0, 0,
	-30, 0, 15, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
}

// idctTestPixelsAC is the expected output for idctTestBlockAC.
// These values are pre-calculated from a known-good IDCT implementation.
var idctTestPixelsAC = [64]byte{
	130, 127, 123, 120, 119, 119, 121, 123,
	130, 128, 124, 121, 120, 120, 122, 123,
	130, 129, 126, 124, 122, 122, 123, 124,
	131, 130, 129, 127, 126, 125, 124, 124,
	132, 132, 131, 130, 129, 127, 126, 125,
	132, 133, 134, 134, 132, 130, 127, 126,
	133, 134, 136, 136, 135, 132, 128, 126,
	133, 135, 137, 137, 136, 133, 129, 126,
}

// idctTestBlockFull is a more complex test block with various non-zero AC coefficients.
// These coefficients were generated by performing a forward DCT on a sample 8x8 pixel block.
var idctTestBlockFull = [64]int32{
	102, -22, -1, 7, 5, -5, -4, 2,
	-25, 19, 10, -8, -2, 4, 3, -4,
	-11, 8, 4, -5, -4, 3, 2, -2,
	-3, 5, 4, -3, -2, 2, 2, -1,
	2, -2, -2, 2, 2, -1, -1, 1,
	-1, 1, 1, -1, -1, 1, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
}

// idctTestPixelsFull is the expected 8x8 pixel block output after applying the IDCT
// to idctTestBlockFull. These values represent the original pixel block and are
// used to verify the correctness of the IDCT implementation with a full set of coefficients.
var idctTestPixelsFull = [64]byte{
	140, 138, 138, 134, 126, 131, 133, 136,
	138, 138, 136, 136, 133, 135, 136, 139,
	138, 138, 135, 138, 142, 140, 141, 142,
	138, 137, 135, 140, 150, 145, 145, 146,
	138, 138, 135, 142, 153, 147, 147, 148,
	138, 139, 138, 141, 148, 147, 148, 148,
	137, 138, 138, 141, 148, 147, 148, 147,
	135, 137, 136, 142, 155, 150, 150, 148,
}

// idctHelper performs a full 8x8 2D IDCT.
func idctHelper(block *[64]int32) [64]byte {
	// We must pass a copy because idct (specifically the Go fallback path) modifies the block in place.
	// The optimized assembly path does not modify the input block.
	b := *block
	var out [64]byte

	// The output stride for a standard 8x8 block is 8.
	idct(&b, out[:], 0, 8)

	return out
}

// printBlock is a helper for formatting an 8x8 block for readable test output.
func printBlock(t *testing.T, block []byte) {
	var buf bytes.Buffer

	for i := 0; i < 64; i++ {
		if i > 0 && i%8 == 0 {
			buf.WriteString("\n")
		}

		buf.WriteString(fmt.Sprintf("%4d", block[i]))
	}

	t.Log("\n" + buf.String())
}

// TestIdctDC verifies the IDCT implementation for the DC-only case.
// This tests the optimization path in both rowIDCT and colIDCT.
func TestIdctDC(t *testing.T) {
	eachTier(t, testIdctDC)
}

func testIdctDC(t *testing.T) {
	block := idctTestBlock
	pixels := idctHelper(&block)

	for i, want := range idctTestPixels {
		if got := pixels[i]; got != want {
			t.Errorf("IDCT DC mismatch at index %d: got %d, want %d", i, got, want)
			t.Log("Got pixels:")
			printBlock(t, pixels[:])
			t.Log("Want pixels:")
			printBlock(t, idctTestPixels[:])
			t.FailNow()
		}
	}
}

// TestIdctAC verifies the IDCT implementation for a general case with AC coefficients.
// This tests the main logic of the AAN fast IDCT algorithm.
func TestIdctAC(t *testing.T) {
	eachTier(t, testIdctAC)
}

func testIdctAC(t *testing.T) {
	block := idctTestBlockAC
	pixels := idctHelper(&block)

	for i, want := range idctTestPixelsAC {
		if got := pixels[i]; got != want {
			t.Errorf("IDCT AC mismatch at index %d: got %d, want %d", i, got, want)
			t.Log("Got pixels:")
			printBlock(t, pixels[:])
			t.Log("Want pixels:")
			printBlock(t, idctTestPixelsAC[:])
			t.FailNow()
		}
	}
}

// TestIdctACStrided verifies the IDCT implementation for a case with a non-8 stride.
func TestIdctACStrided(t *testing.T) {
	eachTier(t, testIdctACStrided)
}

func testIdctACStrided(t *testing.T) {
	const stride = 16
	block := idctTestBlockAC
	// The output buffer must be large enough for 8 rows with the given stride.
	out := make([]byte, 7*stride+8)

	// We must pass a copy because the Go fallback path modifies the block.
	b := block
	idct(&b, out, 0, stride)

	// Verify the output by comparing it to the expected pixels, accounting for the stride.
	for r := 0; r < 8; r++ {
		for c := 0; c < 8; c++ {
			want := idctTestPixelsAC[r*8+c]
			got := out[r*stride+c]
			if got != want {
				t.Errorf("IDCT AC (strided) mismatch at row %d, col %d: got %d, want %d", r, c, got, want)

				// De-stride the output for easier comparison printing
				var gotFlat [64]byte
				for r2 := 0; r2 < 8; r2++ {
					for c2 := 0; c2 < 8; c2++ {
						gotFlat[r2*8+c2] = out[r2*stride+c2]
					}
				}

				t.Log("Got pixels (de-strided):")
				printBlock(t, gotFlat[:])
				t.Log("Want pixels:")
				printBlock(t, idctTestPixelsAC[:])
				t.FailNow()
			}
		}
	}
}

// TestIdctFullBlock verifies the IDCT implementation for a block with many non-zero AC coefficients.
func TestIdctFullBlock(t *testing.T) {
	eachTier(t, testIdctFullBlock)
}

func testIdctFullBlock(t *testing.T) {
	block := idctTestBlockFull
	pixels := idctHelper(&block)

	for i, want := range idctTestPixelsFull {
		if got := pixels[i]; got != want {
			t.Errorf("IDCT Full Block mismatch at index %d: got %d, want %d", i, got, want)
			t.Log("Got pixels:")
			printBlock(t, pixels[:])
			t.Log("Want pixels:")
			printBlock(t, idctTestPixelsFull[:])
			t.FailNow()
		}
	}
}

// TestIdctSaturationUpper tests the upper saturation bound (clamping to 255).
// A DC coefficient of 2047 should result in values > 255 before clipping.
// (2047 / 8) + 128 = 255.875 + 128 = 383.875, which must be clamped to 255.
func TestIdctSaturationUpper(t *testing.T) {
	eachTier(t, testIdctSaturationUpper)
}

func testIdctSaturationUpper(t *testing.T) {
	var block [64]int32
	block[0] = 2047 // Max positive DC value for baseline JPEG
	pixels := idctHelper(&block)

	for i := 0; i < 64; i++ {
		if pixels[i] != 255 {
			t.Errorf("Upper saturation failed at index %d: got %d, want 255", i, pixels[i])
			printBlock(t, pixels[:])
			t.FailNow()
		}
	}
}

// TestIdctSaturationLower tests the lower saturation bound (clamping to 0).
// A DC coefficient of -2047 should result in values < 0 before clipping.
// (-2047 / 8) + 128 = -255.875 + 128 = -127.875, which must be clamped to 0.
func TestIdctSaturationLower(t *testing.T) {
	eachTier(t, testIdctSaturationLower)
}

func testIdctSaturationLower(t *testing.T) {
	var block [64]int32
	block[0] = -2047
	pixels := idctHelper(&block)

	for i := 0; i < 64; i++ {
		if pixels[i] != 0 {
			t.Errorf("Lower saturation failed at index %d: got %d, want 0", i, pixels[i])
			printBlock(t, pixels[:])
			t.FailNow()
		}
	}
}

// BenchmarkIdct measures the performance of the full 8x8 IDCT process.
func BenchmarkIdct(b *testing.B) {
	eachTierB(b, benchmarkIdct)
}

func benchmarkIdct(b *testing.B) {
	// Use the AC test block as a representative input.
	block := idctTestBlockAC
	var out [64]byte

	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		currentBlock := block // Clone
		idct(&currentBlock, out[:], 0, 8)
	}
}

// TestIdctMatchesScalar checks the assembly IDCT against the pure Go one up to
// dequantLimit, the magnitude the decoder clamps coefficients to, and both
// against the reference; limit 0 splits idct8x8MaxL1 over the block, where the
// kernels stop accepting.
func TestIdctMatchesScalar(t *testing.T) {
	eachTier(t, testIdctMatchesScalar)
}

func testIdctMatchesScalar(t *testing.T) {
	rng := rand.New(rand.NewSource(17))

	limits := []int32{0, 4, 255, 2047, 8192}

	for _, lim := range limits {
		for n := 0; n < 2000; n++ {
			var blk [64]int32
			for i := range blk {
				if lim > 0 {
					blk[i] = rng.Int31n(lim)*2 - lim
				}
			}

			for left := idct8x8MaxL1 - 64 + rng.Intn(129); lim == 0 && left > 0; {
				v := 1 + rng.Intn(left)
				left -= v

				if rng.Intn(2) == 0 {
					v = -v
				}

				blk[rng.Intn(64)] += int32(v)
			}

			want := make([]byte, 64)
			got := make([]byte, 64)

			ref := blk
			idctIterative(&ref, want, 0, 8)
			exact := refReduced(&blk, 8)
			idct(&blk, got, 0, 8)

			for i := range want {
				if got[i] != want[i] {
					t.Fatalf("limit %d case %d: pixel %d got %d, want %d", lim, n, i, got[i], want[i])
				}

				// Fixed-point rounding grows with the coefficients; a wrap is far larger.
				if d := math.Abs(float64(want[i]) - exact[i]); d > 8 {
					t.Fatalf("limit %d case %d: pixel %d got %d, reference %.1f", lim, n, i, want[i], exact[i])
				}
			}
		}
	}
}
